plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = "ru.megateam.lab.cli.Main"
}

group = 'ru.megateam.lab'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17  // ← Рекомендую 17 или 21 (24 ещё нет)
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('run') {
    standardInput = System.in
}

tasks.named('test') {
    useJUnitPlatform()
}