plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = "17" //Саша, вот тут версию поменяй, пожалуйста
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}


application {
    mainClass = 'ru.megateam.lab.ui.IncidentApplication'
}

group = 'ru.megateam.lab'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}



dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.google.code.gson:gson:2.10.1'
}

tasks.withType(JavaExec).configureEach {
    if (name == 'run') {
        standardInput = System.in
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.1'
    implementation 'org.postgresql:postgresql:42.7.3'
}
